- type: job
  id: Adjutant
  name: job-name-adjutant
  playTimeTracker: JobAdjutant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 9000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 9000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 9000
    - !type:OverallPlaytimeRequirement
      time: 60000
  weight: 20
  startingGear: AdjGear
  icon: "HeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-hop
  canBeAntag: false
  access:
  - Adjutant
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  minBankBalance: 800
  maxBankBalance: 1200
  department: Command
  wage: 200

- type: startingGear
  id: AdjGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAdj
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: AdjPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtAdj
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
