- type: job
  id: ChiefEngineer
  name: job-name-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 12000
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 30000
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "ChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  minBankBalance: 800
  maxBankBalance: 1200
  department: Command
  wage: 200

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltChiefEngineerFilled
  innerclothingskirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
