- type: job
  id: TechnicalAssistant
  name: job-name-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000
      inverted: true # stop playing intern if you're good at engineering!
  startingGear: TechnicalAssistantGear
  icon: "TechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  minBankBalance: 300
  maxBankBalance: 500

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    head: ClothingHeadHatWelding
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtColorYellow
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
