- type: department
  id: Cargo
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  accountNumber: 1315

- type: department
  id: Civilian
  roles:
  - Bartender
  - Botanist
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - MedicalIntern
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Zookeeper
  - SecurityCadet
  - ServiceWorker
  - TechnicalAssistant
  accountNumber: 1316

- type: department
  id: Command
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - Adjutant
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  accountNumber: 1317

- type: department
  id: Engineering
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  accountNumber: 1318

- type: department
  id: Medical
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  accountNumber: 1319

- type: department
  id: Security
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  accountNumber: 1320

- type: department
  id: Science
  roles:
  - ResearchDirector
  - Scientist
  accountNumber: 1321
