- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "Reporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  minBankBalance: 300
  maxBankBalance: 500

- type: startingGear
  id: ReporterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
